version: '3'
services:
  redis:
    build:
      context: ./infra/redis
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "63793:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - redisdata:/data

  pgsql:
    build:
      context: ./infra/postgres
      dockerfile: Dockerfile
    depends_on:
      - redis
    restart: unless-stopped
    ports:
      - "54323:5432"
    environment:
        POSTGRES_PASSWORD: Xt7#Qp2Lm9Bz
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spi-network

  php-fpm:
    build:
      context: ./infra/php-fpm
      dockerfile: Dockerfile
    depends_on:
      - pgsql
    volumes:
      - ./logs:/var/log
      - ./web:/var/www/html
    networks:
      - spi-network

  nginx:
    build:
      context: ./infra/nginx
      dockerfile: Dockerfile
    ports:
      - "8183:80" 
    volumes:
      - ./logs:/var/log
      - ./web:/var/www/html 
    depends_on:
      - php-fpm
    links:
      - php-fpm
    networks:
      - spi-network

networks:
  spi-network:
    driver: bridge

volumes:
  redisdata:
    driver: local
  pgdata: