version: '3'
services:
  nginx:
    build:
      context: ./infra/nginx
      dockerfile: Dockerfile
    ports:
      - "8183:80" 
    volumes:
      - ./logs:/var/log
      - ./web:/var/www/html 
    depends_on:
      - php-fpm
    links:
      - php-fpm
    networks:
      - spi-network

  php-fpm:
    build:
      context: ./infra/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./logs:/var/log
      - ./web:/var/www/html
      - ~/Sync/Y2/src:/var/www/html/vendor/edortta/yeapf2/src
    networks:
      - spi-network

  # pgsql:
  #   build:
  #     context: ./infra/postgres
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - spi-network

networks:
  spi-network:
    driver: bridge

# volumes:
#   pgdata:
